"""Add Repository Table for Model

Revision ID: 3c45307aeafd
Revises: 
Create Date: 2024-07-31 22:56:14.370749

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3c45307aeafd"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "repository",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("owner", sa.String(length=256), nullable=False),
        sa.Column("url", sa.String(length=256), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_updated_at", sa.DateTime(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("repository", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_repository_owner"), ["owner"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_repository_url"), ["url"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("repository", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_repository_url"))
        batch_op.drop_index(batch_op.f("ix_repository_owner"))

    op.drop_table("repository")
    # ### end Alembic commands ###
